apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  labels:
    app: go-server
spec:
  selector: # selector is used to match the labels of the pods
    matchLabels:
      app: go-server
  replicas: 1 # number of pods to be created
  template: # template is used to create the pods
    metadata:
      labels:
        app: go-server
    spec:
      containers:
        - name: go-server
          image: "jamessonlps1/hello-go:v5.2"
          envFrom:
            - configMapRef:
                name: go-server-env
          volumeMounts:
            - mountPath: "/go/files"
              name: config
      volumes:
        - name: config
          configMap:
            name: configmap-data
            items:
              - key: names
                path: file.txt
