apiVersion: v1
kind: Service
metadata:
  name: go-server-service
spec:
  selector: # Filtra os pods que o serviço irá direcionar o tráfego
    app: go-server
  type: LoadBalancer # Libera um IP externo para acessar o serviço
  ports:
    - name: http-go-server-service
      protocol: TCP
      port: 80 # Porta do serviço
      targetPort: 8000 # Porta do container
